
## 🎯 **Roadmap Belajar TensorFlow**  

### 🔹 **1. Persiapan Awal**  
✅ **Pemrograman Python**  
- Variabel, tipe data, kontrol alur  
- Fungsi & OOP di Python  
- List comprehension & lambda function  

✅ **Dasar-dasar Matematika untuk AI**  
- Aljabar linear (matriks & vektor)  
- Kalkulus dasar (turunan & gradien)  
- Probabilitas & statistik  

✅ **Pemrograman dengan NumPy & Pandas**  
- Operasi array dengan NumPy  
- Manipulasi dataset dengan Pandas  

---

### 🔹 **2. Memulai dengan TensorFlow**  
✅ **Pengenalan TensorFlow**  
- Instalasi TensorFlow  
- Konsep dasar: Tensor, operasi, sesi (Eager Execution)  
- Struktur model: Sequential vs Functional API  

✅ **Manipulasi Data dengan TensorFlow**  
- Menggunakan `tf.data` untuk loading dataset  
- Augmentasi data dengan `tf.image`  
- Normalisasi dan pre-processing data  

✅ **Implementasi Model Sederhana**  
- Membuat model regresi linear  
- Implementasi model klasifikasi dasar  

---

### 🔹 **3. Pemodelan dengan TensorFlow & Keras**  
✅ **Membangun Model dengan Keras API**  
- Membuat model Sequential  
- Menggunakan layer seperti `Dense`, `Dropout`, `BatchNormalization`  
- Optimizer & loss function  

✅ **Pelatihan dan Evaluasi Model**  
- Backpropagation & optimisasi  
- Visualisasi dengan TensorBoard  
- Evaluasi model dengan `accuracy`, `loss`, dll.  

✅ **Handling Overfitting & Hyperparameter Tuning**  
- Regularisasi: Dropout, L1/L2  
- Hyperparameter tuning dengan Keras Tuner  

---

### 🔹 **4. Computer Vision dengan TensorFlow**  
✅ **Menggunakan CNN untuk Image Classification**  
- Convolutional & Pooling layer  
- Transfer Learning dengan model pre-trained (MobileNet, ResNet)  
- Object Detection dengan TensorFlow Hub  

✅ **Image Segmentation & GANs**  
- Implementasi U-Net untuk segmentasi  
- Generative Adversarial Networks (GANs)  

---

### 🔹 **5. Natural Language Processing (NLP) dengan TensorFlow**  
✅ **Pemrosesan Teks & Word Embeddings**  
- Tokenisasi & sequence padding  
- Word2Vec & embeddings dengan `tf.keras.layers.Embedding`  

✅ **Membangun Model NLP dengan RNN & Transformer**  
- Implementasi LSTM & GRU  
- Membangun Transformer (BERT, GPT, dll.) dengan TensorFlow  

---

### 🔹 **6. Model Deployment & Production**  
✅ **Menggunakan TensorFlow Serving**  
- Menyimpan & memuat model TensorFlow  
- Deploy model sebagai REST API  

✅ **Optimasi Model untuk Mobile & Web**  
- Konversi model ke TensorFlow Lite  
- Menggunakan TensorFlow.js untuk aplikasi web  

✅ **MLOps dengan TensorFlow Extended (TFX)**  
- Automasi pipeline machine learning  
- Model monitoring & deployment skala besar  

---

## 🚀 **Sumber Belajar**  
🔹 Dokumentasi TensorFlow: [https://www.tensorflow.org](https://www.tensorflow.org)  
🔹 Google Colab untuk latihan interaktif  
🔹 Kaggle & TensorFlow Hub untuk dataset & model pre-trained  

---

Roadmap ini bisa disesuaikan dengan minat dan kebutuhanmu. Kamu lebih tertarik ke **Computer Vision** atau **NLP**? 😊

In [6]:
import tensorflow as tf
from tensorflow.keras import layers, Model, Input

In [24]:
print("tensor flow version = " + tf.__version__)
# membuat tensor sederhana
a  = tf.constant(9) #tensor saklar
b  = tf.constant(6)
c = a+b #operasi tensor jumlah
print(f"nilai a: {a}")
print(f"nilai b: {b}")
print(f"nilai c: {c}")
matrix = tf.constant([[1,2],[3,4]])
print("matrix =")
print(matrix.numpy())
matrix_1D = tf.constant([1,2,3,4,5])
print("matrix =")
print(matrix_1D.numpy())
var = tf.Variable(100)
print("nilai awal = ", var.numpy())
var.assign(50)
print("nilai yang sudah diubah =", var.numpy())
A = tf.constant([[1, 2], [3, 4]])
B = tf.constant([[5, 6], [7, 8]])

hasil_perkalian = tf.matmul(A, B) 
print(hasil_perkalian.numpy())

tensor flow version = 2.18.0
nilai a: 9
nilai b: 6
nilai c: 15
matrix =
[[1 2]
 [3 4]]
matrix =
[1 2 3 4 5]
nilai awal =  100
nilai yang sudah diubah = 50
[[19 22]
 [43 50]]


In [ ]:
# sequintal api
model = tf.keras.Sequential([
    layers.Dense(64, activation='relu',input_shape =(10,)),
    layers.Dense(32,activation='relu'), # hidden layer
    layers.Dense(1,activation='sigmoid')# output layer (misal untuk klasifikasi biner)
])
model.summary()

c:\Users\addid\AppData\Local\Programs\Python\Python312\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_4 (Dense)                 │ (None, 64)             │           704 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,817 (11.00 KB)

 Trainable params: 2,817 (11.00 KB)

 Non-trainable params: 0 (0.00 B)

In [10]:
# functional api
# definisi input
inputs = Input(shape=(10,))
# Definisi layer
x = layers.Dense(64,activation='relu')(inputs)
x = layers.Dense(32,activation='relu')(x)
outputs = layers.Dense(1,activation='sigmoid')(x)
model = Model(inputs=inputs, outputs=outputs)
model.summary()

Model: "functional_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ input_layer_5 (InputLayer)      │ (None, 10)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_16 (Dense)                │ (None, 64)             │           704 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_17 (Dense)                │ (None, 32)             │         2,080 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_18 (Dense)                │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,817 (11.00 KB)

 Trainable params: 2,817 (11.00 KB)

 Non-trainable params: 0 (0.00 B)

1️⃣Input Layer → layers.Dense(128, activation='relu', input_shape=(10,))
Dense(128, activation='relu') → Layer ini memiliki 128 neuron.
input_shape=(10,) → Model menerima data dengan 10 fitur sebagai input.
Contohnya: Jika dataset berisi informasi tentang pasien dengan 10 variabel (seperti umur, tekanan darah, kolesterol, dll.), maka input memiliki 10 fitur.
activation='relu' → Fungsi aktivasi ReLU (Rectified Linear Unit) digunakan agar model dapat menangkap pola lebih baik.
💡 Apa yang Terjadi di Sini?
Input masuk ke 128 neuron.
Setiap neuron menghitung nilai output berdasarkan bobot (w) dan bias (b), lalu menerapkan ReLU.
ReLU(x) = max(0, x) (nilai negatif jadi nol, nilai positif tetap).

2️⃣ Hidden Layer → layers.Dense(64, activation='relu')
Dense(64, activation='relu') → Layer ini memiliki 64 neuron.
Kenapa masih pakai activation='relu'?
Karena ReLU menghindari masalah vanishing gradient, sehingga model bisa belajar lebih cepat.
Hidden layer ini bertugas untuk menangkap pola lebih kompleks dari data.
💡 Apa yang Terjadi di Sini?

Data dari layer sebelumnya masuk ke 64 neuron.
Setiap neuron menerima input, mengalikan dengan bobot, menambahkan bias, lalu menerapkan ReLU.
Informasi yang lebih bermakna diteruskan ke layer berikutnya.

3️⃣ Output Layer → layers.Dense(1, activation='sigmoid')
Dense(1, activation='sigmoid') → Layer ini memiliki 1 neuron karena hanya ada satu output.
Kenapa pakai activation='sigmoid'?
Karena kita ingin model melakukan klasifikasi biner (dua kelas: 0 atau 1).
Fungsi sigmoid mengubah output menjadi nilai antara 0 dan 1 (probabilitas).

 
💡 Apa yang Terjadi di Sini?

Setelah data diproses oleh hidden layer, neuron output mengambil informasi terakhir.
Fungsi sigmoid memastikan nilai output berada di rentang 0 sampai 1.
Hasil ini bisa diinterpretasikan sebagai probabilitas dari kelas 1 (misalnya "positif" atau "berhasil").

